# Generated by Django 5.1.4 on 2025-01-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hoteluser_is_verified_hotelvendor_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
