# Generated by Django 5.1.4 on 2025-01-06 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_hotel_hotel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelvendor',
            name='business_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
