# Generated by Django 5.1.4 on 2025-01-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_hoteluser_options_alter_hotelvendor_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ameneties',
            new_name='Amenities',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='ameneties',
            new_name='amenities',
        ),
    ]
